export default {
  BASE_URL: 'http://localhost:3000',
  MIN_TRANSACTION_AMOUNT: 10000,
  MAX_TRANSACTION_AMOUNT: 10000000,
  TYPE_TRANSFER: 'TRANSFER',
  TYPE_TOP_UP: 'TOP_UP',
  SUCCESS_NOTIFICATION_COLOR: '#00c853',
  ERROR_NOTIFICATION_COLOR: '#dd2c00',
  WRONG_PASSWORD_EMAIL: 'Username or Password is incorrect!'
};
